doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            #url: 'localhost'
            # connection: default
            # requires DoctrineCacheBundle
            # caches:
            #     meta: doctrine_cache.providers.phpcr_meta
            #     nodes: doctrine_cache.providers.phpcr_nodes
            # enable logging
            # logging: true
            # enable profiling in the debug toolbar.
            # profiling: true
        workspace: "%env(PHPCR_WORKSPACE)%"
        username: "%env(PHPCR_USER)%"
        password: "%env(PHPCR_PASSWORD)%"
    odm:
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Document'
                prefix: 'App\Document'
                alias: App
